spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/pro
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# UserService의 public String key값
#     @Value("${jwt.token.secret}") // ${jwt.token.secret} ==> yml파일 어노테이션 라이브러리 롬복 x 스프링프레임워크
#    private String key;
jwt:
  token:
    secret: secret